# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cd6f306d024743585ece9b2930731d7e15884791832fcdf892366f2c1ae5479ebd8422ab08e2d85840b7687a51f26f35fbe7a1fd9bd0535c6c91bb4289147d7

test:
  secret_key_base: f1d8e815bb1a334808b45e62627dd65c9d33a732a8ebaaf6a4cdf327af2647d8926e1dbc40f6ae0fd12159bc8a71f40d302e59e72dae267e4cd1eba9ec40510e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
